name: Firmware release
on:
  pull_request:

jobs:
  firmware-build:
    name: Firmware build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Virutalnenv install
      run: |
        pip install --upgrade virtualenv
        virtualenv -p python3 venv

    - name: Installing platformio
      run: pip3 install -U platformio

    - name: Building a firmware for STM32
      run: git submodule update --init --recursive && pio run
