name: Firmware release
on:
  pull_request:

jobs:
  firmware-build:
    name: Firmware build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Installing platformio
    #   run: pip3 install -U platformio

    # - name: Building a firmware for STM32
    #   run: git submodule update --init --recursive && pio run

    - name: Building a firmware for STM32
      run: docker compose up